# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1F5kF_SJ5VW4DEk0QaDkaawE1MvuAQQqB
"""

#TRAIN-TEST-SPLIT

import pandas as pd

df = pd.read_csv("carprices.csv")

df

# Commented out IPython magic to ensure Python compatibility.
import matplotlib.pyplot as plt
# %matplotlib inline

plt.scatter(df['Mileage'] , df['Sell Price($)'])

plt.scatter(df['Age(yrs)'] , df['Sell Price($)'])

X = df.drop('Sell Price($)' , axis = 'columns')

X

Y = df['Sell Price($)']
Y

from sklearn.model_selection import train_test_split

X_train , X_test , Y_train , Y_test = train_test_split(X , Y , test_size = 0.2 , random_state=10)

from sklearn.linear_model import LinearRegression

model = LinearRegression()

model.fit(X_train , Y_train)

model.predict(X_test)

Y_test

model.score(X_test , Y_test)

import pickle

with open('model_pickle' , 'wb') as f:
    pickle.dump(model , f)

with open('model_pickle' , 'rb') as f:
    mp = pickle.load(f)

